FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY package-lock.json* ./

RUN npm install --legacy-peer-deps

# ✅ Forcer l'installation de Stripe (même si non présent dans le lockfile)
RUN npm install @stripe/stripe-js @stripe/react-stripe-js stripe --legacy-peer-deps

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]